# Generated by Django 2.2 on 2020-10-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedeSocial', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('conteudo', models.CharField(max_length=100, verbose_name='Conteudo')),
                ('imagem', models.ImageField(upload_to='media/', verbose_name='Imagem 1920x780')),
            ],
        ),
        migrations.CreateModel(
            name='Banner3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('conteudo', models.CharField(max_length=100, verbose_name='Conteudo')),
                ('imagem', models.ImageField(upload_to='media/', verbose_name='Imagem 1920x780')),
            ],
        ),
    ]
