# Generated by Django 2.2.4 on 2020-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedeSocial', '0003_banner2_banner3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Titulo')),
                ('video', models.FileField(upload_to='media/', verbose_name='Apresentação')),
            ],
        ),
    ]
