# Generated by Django 2.2.4 on 2020-10-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedeSocial', '0004_institucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=100, verbose_name='Pessoa')),
                ('data', models.CharField(max_length=100, verbose_name='Conteudo')),
                ('imagem', models.ImageField(upload_to='media/', verbose_name='Imagem da Pessoa')),
            ],
        ),
    ]
