# Generated by Django 2.2.4 on 2020-10-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedeSocial', '0005_aniversario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniversario',
            name='data',
            field=models.CharField(max_length=100, verbose_name='Data de Aniversario'),
        ),
    ]
